language: r
cache: packages

script:
  - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: 2019